from_latest_tag = true
ignore_merge_commits = false
branch_whitelist = ["main"]

pre_bump_hooks = []
post_bump_hooks = [
  "git push",
  "git push --tags"
]

pre_package_bump_hooks = []
post_package_bump_hooks = []

tag_prefix = "v"

[commit_types]
tweak = { changelog_title = "Tweaks" }
nit = { changelog_title = "Nitpicks, changes with no side effect" }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "minemacs"
owner = "abougouffa"
authors = [
  { signature = "Abdelhak Bougouffa", username = "abougouffa" }
]

[bump_profiles]

[packages]
